-- =====================================================================================
-- 1. CREACIÓN DE TABLAS (Catálogos, Ventas, Inventario, Nómina y Promociones)
-- =====================================================================================

CREATE TABLE clientes (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL,
    telefono TEXT UNIQUE,
    visitas_totales INTEGER DEFAULT 0,
    puntos_lealtad INTEGER DEFAULT 0,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE empleados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    apellido TEXT NOT NULL,
    telefono TEXT,
    salario NUMERIC(10, 2) NOT NULL,
    dia_pago INTEGER NOT NULL
);

CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    precio NUMERIC(10, 2) NOT NULL,
    categoria TEXT NOT NULL,
    controla_inventario BOOLEAN DEFAULT FALSE,
    stock_actual INTEGER DEFAULT 0,
    stock_minimo INTEGER DEFAULT 0,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE mesas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_mesa TEXT NOT NULL,
    estado TEXT DEFAULT 'Libre'
);

CREATE TABLE promociones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    descripcion TEXT NOT NULL,
    imagen_url TEXT,
    fecha_publicacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    fecha_vencimiento DATE,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE ordenes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa_id BIGINT REFERENCES mesas(id),
    cliente_id UUID REFERENCES clientes(id), -- Vinculado al usuario logueado
    tipo_servicio TEXT NOT NULL,
    fecha_apertura TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    estado TEXT DEFAULT 'Abierta'
);

CREATE TABLE detalle_orden (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id BIGINT NOT NULL REFERENCES ordenes(id) ON DELETE CASCADE,
    producto_id BIGINT NOT NULL REFERENCES productos(id),
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10, 2) NOT NULL,
    estado_pago TEXT DEFAULT 'Pendiente'
);

CREATE TABLE transacciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id BIGINT NOT NULL REFERENCES ordenes(id),
    monto NUMERIC(10, 2) NOT NULL,
    metodo_pago TEXT NOT NULL,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE venta_diaria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL UNIQUE,
    total_efectivo NUMERIC(10, 2) DEFAULT 0,
    total_tarjeta NUMERIC(10, 2) DEFAULT 0,
    total_global NUMERIC(10, 2) NOT NULL,
    hora_cierre TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE historial_pagos_empleados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id BIGINT NOT NULL REFERENCES empleados(id),
    monto NUMERIC(10, 2) NOT NULL,
    fecha_pago DATE DEFAULT CURRENT_DATE,
    notas TEXT
);

-- =====================================================================================
-- 2. ACTIVACIÓN DEL ESCUDO RLS (Row Level Security)
-- =====================================================================================

ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE empleados ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE mesas ENABLE ROW LEVEL SECURITY;
ALTER TABLE promociones ENABLE ROW LEVEL SECURITY;
ALTER TABLE ordenes ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalle_orden ENABLE ROW LEVEL SECURITY;
ALTER TABLE transacciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE venta_diaria ENABLE ROW LEVEL SECURITY;
ALTER TABLE historial_pagos_empleados ENABLE ROW LEVEL SECURITY;

-- =====================================================================================
-- 3. DEFINICIÓN DE POLÍTICAS DE SEGURIDAD (POLICIES)
-- =====================================================================================
-- NOTA: Asumimos que los empleados/admins tienen un metadato {"rol": "empleado"} 
--       o {"rol": "admin"} al ser registrados.

-- A. SEGURIDAD DE CLIENTES
-- Los clientes solo pueden ver y editar su propia fila. El staff puede ver y editar a todos.
CREATE POLICY "Clientes ven su propio perfil" ON clientes FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Clientes actualizan su propio perfil" ON clientes FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Staff controla clientes" ON clientes FOR ALL USING ((auth.jwt() -> 'user_metadata' ->> 'rol') IN ('admin', 'empleado'));

-- B. SEGURIDAD ADMINISTRATIVA (Nómina, Ventas, Transacciones)
-- Estas tablas están totalmente bloqueadas para los clientes.
CREATE POLICY "Solo staff gestiona empleados" ON empleados FOR ALL USING ((auth.jwt() -> 'user_metadata' ->> 'rol') IN ('admin', 'empleado'));
CREATE POLICY "Solo staff gestiona ventas diarias" ON venta_diaria FOR ALL USING ((auth.jwt() -> 'user_metadata' ->> 'rol') IN ('admin', 'empleado'));
CREATE POLICY "Solo staff gestiona pagos" ON historial_pagos_empleados FOR ALL USING ((auth.jwt() -> 'user_metadata' ->> 'rol') IN ('admin', 'empleado'));
CREATE POLICY "Solo staff gestiona transacciones" ON transacciones FOR ALL USING ((auth.jwt() -> 'user_metadata' ->> 'rol') IN ('admin', 'empleado'));

-- C. DATOS PÚBLICOS (Lectura para todos, Escritura solo para Staff)
-- Permite que la app del cliente descargue el menú y las promos, pero no las modifique.
CREATE POLICY "Cualquiera lee productos" ON productos FOR SELECT USING (true);
CREATE POLICY "Staff modifica productos" ON productos FOR ALL USING ((auth.jwt() -> 'user_metadata' ->> 'rol') IN ('admin', 'empleado'));

CREATE POLICY "Cualquiera lee mesas" ON mesas FOR SELECT USING (true);
CREATE POLICY "Staff modifica mesas" ON mesas FOR ALL USING ((auth.jwt() -> 'user_metadata' ->> 'rol') IN ('admin', 'empleado'));

CREATE POLICY "Cualquiera lee promociones" ON promociones FOR SELECT USING (true);
CREATE POLICY "Staff modifica promociones" ON promociones FOR ALL USING ((auth.jwt() -> 'user_metadata' ->> 'rol') IN ('admin', 'empleado'));

-- D. SEGURIDAD DE VENTAS (Órdenes)
-- El staff tiene acceso a todo. Los clientes solo pueden LEER su propio historial de pedidos.
CREATE POLICY "Staff gestiona ordenes completas" ON ordenes FOR ALL USING ((auth.jwt() -> 'user_metadata' ->> 'rol') IN ('admin', 'empleado'));
CREATE POLICY "Clientes ven sus propias ordenes" ON ordenes FOR SELECT USING (auth.uid() = cliente_id);

CREATE POLICY "Staff gestiona detalles de orden" ON detalle_orden FOR ALL USING ((auth.jwt() -> 'user_metadata' ->> 'rol') IN ('admin', 'empleado'));
CREATE POLICY "Clientes ven los detalles de sus ordenes" ON detalle_orden FOR SELECT USING (
    orden_id IN (SELECT id FROM ordenes WHERE cliente_id = auth.uid())
);